apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-monitor-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-monitor
  template:
    metadata:
      labels:
        app: flask-monitor
    spec:
      containers:
      - name: flask-container
        image: rm13rotem/flask-aws-monitor:latest
        ports:
        - containerPort: 5001
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: AWS_SECRET_ACCESS_KEY
        - name: REGION
          value: us-east-1
